openapi: 3.1.0
info:
  title: Presto's HTTP Protocol
  version: 0.0.1
paths: {
  /v1/node:
    get:
      summary: Returns a list of nodes known to a Presto Server.
      description: This call doesn’t require a query parameter of headers, it simply returns an array with each known node in a Presto installation.
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: integer
                minimum: 1
                maximum: 100

} # No endpoints defined
